/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;
import java.util.*;

import java.sql.*;

/**
 *
 * @author Dylan
 */

public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    Connection conn = null;
    Statement state = null;
    Statement state2 = null;
	Statement stateD = null;
    ResultSet rs = null;
    ResultSet rs2 = null;
	ResultSet descs = null;
	List<String> pokeDescs = new ArrayList<String>();
	String[] descriptions;
    int index;
    int current = 1;
	int currentDescription = 0;
	boolean rotated = false;
	boolean shiny = false;
    java.awt.Color base = new java.awt.Color(0, 0, 0);
    java.awt.Color grassC = new java.awt.Color(7, 127, 63);
    java.awt.Color fireC = new java.awt.Color(242, 127, 19);
    java.awt.Color waterC = new java.awt.Color(16, 125, 209);
    java.awt.Color normalC = new java.awt.Color(153, 153, 153);
    java.awt.Color fightingC = new java.awt.Color(180, 85, 64);
    java.awt.Color flyingC = new java.awt.Color(121, 165, 255);
    java.awt.Color electricC = new java.awt.Color(255, 207, 63);
    java.awt.Color groundC = new java.awt.Color(206, 172, 78);
    java.awt.Color iceC = new java.awt.Color(164, 207, 207);
    java.awt.Color rockC = new java.awt.Color(186, 160, 46);
    java.awt.Color psychicC = new java.awt.Color(237, 91, 139);
    java.awt.Color ghostC = new java.awt.Color(105, 87, 136);
    java.awt.Color darkC = new java.awt.Color(111, 88, 70);
    java.awt.Color bugC = new java.awt.Color(167, 183, 31);
    java.awt.Color poisonC = new java.awt.Color(149, 69, 154);
    java.awt.Color steelC = new java.awt.Color(183, 183, 194);
    java.awt.Color fairyC = new java.awt.Color(251, 180, 242);
    java.awt.Color dragonC = new java.awt.Color(104, 51, 242);
	java.awt.CardLayout cl = new java.awt.CardLayout();
    public mainWindow() {
        initComponents();
        try
        {
            String driver = "org.apache.derby.jdbc.EmbeddedDriver";
            Class.forName(driver).newInstance();

            String jdbcUrl = "jdbc:derby:./pokemon";
            conn = DriverManager.getConnection(jdbcUrl, "", "");
            
            state = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            state2 = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
			stateD = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);

            String sql_query = ("select pokename from MAIN_PUCHAMONES");
            rs = state.executeQuery(sql_query);
            
            index = 1;
            
            setPokes();
        }
        catch(SQLException e)
        {
            System.err.println(e.getMessage());
        }
        catch(ClassNotFoundException e)
        {
            System.err.println(e.getMessage());
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
		dexcriptionContainer.setOpaque(false);
		dexcriptionContainer.getViewport().setOpaque(false);
		dexcriptionContainer.setBorder(null);
		dexcriptionContainer.setViewportBorder(null);
		
		dexcription.setBorder(null);
		dexcription.setBackground(new java.awt.Color(0,0,0,0));
		dexcription.setWrapStyleWord(true);
		jPanel1.setLayout(cl);
		cl.addLayoutComponent(listViewPanel, "List view");
		cl.addLayoutComponent(infoViewPanel, "Info view");
		cl.show(jPanel1, "List view");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        listViewPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        firstPokeImg = new javax.swing.JLabel();
        firstPoke = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        secondPokeImg = new javax.swing.JLabel();
        secondPoke = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        thirdPokeImg = new javax.swing.JLabel();
        thirdPoke = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        fourthPokeImg = new javax.swing.JLabel();
        fourthPoke = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        fifthPokeImg = new javax.swing.JLabel();
        fifthPoke = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        goUpList = new javax.swing.JLabel();
        goDownList = new javax.swing.JLabel();
        infoViewPanel = new javax.swing.JPanel();
        PokeInfoName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        pokeSprite = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        dexcriptionContainer = new javax.swing.JScrollPane();
        dexcription = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PokeType1 = new javax.swing.JPanel();
        PokeTypeLabel1 = new javax.swing.JLabel();
        PokeType2 = new javax.swing.JPanel();
        PokeTypeLabel2 = new javax.swing.JLabel();
        pokeNo = new javax.swing.JLabel();
        nextDesc = new javax.swing.JLabel();
        prevDesc = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        pokeShape = new javax.swing.JLabel();
        nextPokeInfo = new javax.swing.JLabel();
        prevPokeInfo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("◀");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 290));
        setMinimumSize(new java.awt.Dimension(480, 290));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(480, 290));
        jPanel1.setLayout(new java.awt.CardLayout());

        listViewPanel.setBackground(new java.awt.Color(43, 45, 46));
        listViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(112, 193, 112));

        jPanel7.setOpaque(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(221, 64, 64));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SEARCH");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        listViewPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 296));

        jPanel3.setBackground(new java.awt.Color(43, 45, 46));
        jPanel3.setLayout(new java.awt.GridLayout(5, 1, 0, 6));

        jPanel5.setBackground(new java.awt.Color(61, 62, 66));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(51, 153, 255));

        firstPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/abra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(firstPokeImg)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(firstPokeImg)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        firstPoke.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        firstPoke.setForeground(new java.awt.Color(255, 255, 255));
        firstPoke.setText("First Pokémon");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(firstPoke)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstPoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(61, 62, 66));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(51, 153, 255));

        secondPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/abra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(secondPokeImg)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(secondPokeImg)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        secondPoke.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        secondPoke.setForeground(new java.awt.Color(255, 255, 255));
        secondPoke.setText("Second Pokémon");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(secondPoke)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secondPoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6);

        jPanel13.setBackground(new java.awt.Color(61, 62, 66));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(51, 153, 255));

        thirdPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/abra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(thirdPokeImg)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(thirdPokeImg)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        thirdPoke.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        thirdPoke.setForeground(new java.awt.Color(255, 255, 255));
        thirdPoke.setText("Third Pokémon");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thirdPoke)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thirdPoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel13);

        jPanel15.setBackground(new java.awt.Color(61, 62, 66));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jPanel16.setBackground(new java.awt.Color(51, 153, 255));

        fourthPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/abra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(fourthPokeImg)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fourthPokeImg)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        fourthPoke.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        fourthPoke.setForeground(new java.awt.Color(255, 255, 255));
        fourthPoke.setText("Fourth Pokémon");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fourthPoke)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fourthPoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel15);

        jPanel17.setBackground(new java.awt.Color(61, 62, 66));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });

        jPanel18.setBackground(new java.awt.Color(51, 153, 255));

        fifthPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/abra.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(fifthPokeImg)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fifthPokeImg)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );

        fifthPoke.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        fifthPoke.setForeground(new java.awt.Color(255, 255, 255));
        fifthPoke.setText("Fifth Pokémon");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fifthPoke)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fifthPoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel17);

        listViewPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 26, 290, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        listViewPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 20));

        goUpList.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        goUpList.setForeground(new java.awt.Color(255, 255, 255));
        goUpList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goUpList.setText("▲");
        goUpList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goUpListMouseClicked(evt);
            }
        });
        listViewPanel.add(goUpList, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 6, 51, -1));

        goDownList.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        goDownList.setForeground(new java.awt.Color(255, 255, 255));
        goDownList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        goDownList.setText("▼");
        goDownList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goDownListMouseClicked(evt);
            }
        });
        listViewPanel.add(goDownList, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 271, 51, -1));

        jPanel1.add(listViewPanel, "card2");

        infoViewPanel.setBackground(new java.awt.Color(51, 51, 51));
        infoViewPanel.setEnabled(false);
        infoViewPanel.setFocusable(false);
        infoViewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PokeInfoName.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PokeInfoName.setForeground(new java.awt.Color(255, 255, 255));
        PokeInfoName.setText("Fletchinder");
        infoViewPanel.add(PokeInfoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 275, 31));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("🢔");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        infoViewPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 30, 30));

        jPanel10.setBackground(new java.awt.Color(51, 153, 255));

        pokeSprite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/63.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pokeSprite, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pokeSprite, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        infoViewPanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 100, 100));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("x");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        infoViewPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 20));

        jPanel20.setBackground(new java.awt.Color(73, 73, 77));
        jPanel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.setPreferredSize(new java.awt.Dimension(470, 108));

        dexcriptionContainer.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        dexcriptionContainer.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        dexcriptionContainer.setFocusable(false);
        dexcriptionContainer.setWheelScrollingEnabled(false);

        dexcription.setEditable(false);
        dexcription.setColumns(20);
        dexcription.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        dexcription.setForeground(new java.awt.Color(255, 255, 255));
        dexcription.setLineWrap(true);
        dexcription.setRows(5);
        dexcription.setFocusable(false);
        dexcription.setOpaque(false);
        dexcriptionContainer.setViewportView(dexcription);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dexcriptionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dexcriptionContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        infoViewPanel.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 164, 410, -1));

        jPanel9.setBackground(new java.awt.Color(73, 73, 77));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        infoViewPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 143, -1, 20));

        PokeTypeLabel1.setBackground(new java.awt.Color(247, 247, 247));
        PokeTypeLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PokeTypeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PokeTypeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PokeTypeLabel1.setText("Type 1");
        PokeTypeLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PokeType1Layout = new javax.swing.GroupLayout(PokeType1);
        PokeType1.setLayout(PokeType1Layout);
        PokeType1Layout.setHorizontalGroup(
            PokeType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PokeTypeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );
        PokeType1Layout.setVerticalGroup(
            PokeType1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PokeTypeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        infoViewPanel.add(PokeType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, -1, -1));

        PokeTypeLabel2.setBackground(new java.awt.Color(255, 255, 255));
        PokeTypeLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PokeTypeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        PokeTypeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PokeTypeLabel2.setText("Type 2");

        javax.swing.GroupLayout PokeType2Layout = new javax.swing.GroupLayout(PokeType2);
        PokeType2.setLayout(PokeType2Layout);
        PokeType2Layout.setHorizontalGroup(
            PokeType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PokeTypeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );
        PokeType2Layout.setVerticalGroup(
            PokeType2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PokeTypeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        infoViewPanel.add(PokeType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 70, -1, -1));

        pokeNo.setForeground(new java.awt.Color(255, 255, 255));
        pokeNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pokeNo.setText("#001");
        infoViewPanel.add(pokeNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 60, 30));

        nextDesc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nextDesc.setForeground(new java.awt.Color(255, 255, 255));
        nextDesc.setText("▶");
        nextDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextDescMouseClicked(evt);
            }
        });
        infoViewPanel.add(nextDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        prevDesc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        prevDesc.setForeground(new java.awt.Color(255, 255, 255));
        prevDesc.setText("◀");
        prevDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevDescMouseClicked(evt);
            }
        });
        infoViewPanel.add(prevDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });

        pokeShape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pokeShape, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pokeShape, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        infoViewPanel.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, 40));

        nextPokeInfo.setForeground(new java.awt.Color(255, 255, 255));
        nextPokeInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextPokeInfo.setText("▶");
        nextPokeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextPokeInfoMouseClicked(evt);
            }
        });
        infoViewPanel.add(nextPokeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 30, 30));

        prevPokeInfo.setForeground(new java.awt.Color(255, 255, 255));
        prevPokeInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prevPokeInfo.setText("◀");
        prevPokeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevPokeInfoMouseClicked(evt);
            }
        });
        infoViewPanel.add(prevPokeInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("🟊");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        infoViewPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 40, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("⟲");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        infoViewPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 40, 20));

        jPanel1.add(infoViewPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void goDownListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goDownListMouseClicked
        index = index + 5;
        setPokes();
    }//GEN-LAST:event_goDownListMouseClicked

    private void goUpListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goUpListMouseClicked
        if(index > 1)
        {
            index = index - 5;
            setPokes();
        }
        
    }//GEN-LAST:event_goUpListMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        setPokeDesc();
    }//GEN-LAST:event_jPanel19MouseClicked

    private void prevPokeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevPokeInfoMouseClicked
        if(current > 1)
        {
           current -= 1;
           setPokeDesc();
        }
    }//GEN-LAST:event_prevPokeInfoMouseClicked

    private void nextPokeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextPokeInfoMouseClicked
        current += 1;
        setPokeDesc();
    }//GEN-LAST:event_nextPokeInfoMouseClicked

    private void nextDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextDescMouseClicked
        currentDescription += 1;
		if(currentDescription == (descriptions.length - 1))
			nextDesc.setVisible(false);
		if(currentDescription > 0)
			prevDesc.setVisible(true);
		dexcription.setText(descriptions[currentDescription]);
    }//GEN-LAST:event_nextDescMouseClicked

    private void prevDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevDescMouseClicked
        currentDescription -= 1;
		if(currentDescription == 0)
			prevDesc.setVisible(false);
		nextDesc.setVisible(true);
		dexcription.setText(descriptions[currentDescription]);
    }//GEN-LAST:event_prevDescMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        current = index;
		setPokeDesc();
		cl.show(jPanel1, "Info view");
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        cl.show(jPanel1, "List view");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        current = index + 1;
		setPokeDesc();
		cl.show(jPanel1, "Info view");
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        current = index + 2;
		setPokeDesc();
		cl.show(jPanel1, "Info view");
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        current = index + 3;
		setPokeDesc();
		cl.show(jPanel1, "Info view");
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        current = index + 4;
		setPokeDesc();
		cl.show(jPanel1, "Info view");
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        rotated = !rotated;
		try
		{
			if(rotated)
				if(shiny)
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+"sb.png")));
				else
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+"b.png")));
			else if(shiny)
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+"s.png")));
				else
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+".png")));
		}
		catch(SQLException e) {System.err.println(e.getMessage());}
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        shiny = !shiny;
		try
		{
			if(shiny)
				if(rotated)
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+"sb.png")));
				else
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+"s.png")));
			else if(rotated)
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+"b.png")));
				else
					pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+".png")));
		}
		catch(SQLException e) {System.err.println(e.getMessage());}
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }
    
    public void setPokes()
    {
        try
        {
            if(index <= 5)
                goUpList.setVisible(false);
            else
                goUpList.setVisible(true);
                
            rs.absolute(index);
            firstPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/"+rs.getString("POKENAME").toLowerCase()+".png")));
            firstPoke.setText(index+" - "+rs.getString("POKENAME"));

            rs.absolute(index + 1);
            secondPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/"+rs.getString("POKENAME").toLowerCase()+".png")));
            secondPoke.setText((index + 1)+" - "+rs.getString("POKENAME"));

            rs.absolute(index + 2);
            thirdPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/"+rs.getString("POKENAME").toLowerCase()+".png")));
            thirdPoke.setText((index + 2)+" - "+rs.getString("POKENAME"));

            rs.absolute(index + 3);
            fourthPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/"+rs.getString("POKENAME").toLowerCase()+".png")));
            fourthPoke.setText((index + 3)+" - "+rs.getString("POKENAME"));

            rs.absolute(index + 4);
            fifthPokeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/pokes/"+rs.getString("POKENAME").toLowerCase()+".png")));
            fifthPoke.setText((index + 4)+" - "+rs.getString("POKENAME"));
        }
        catch(SQLException e) {System.out.println(e.getMessage());}
        
    }
    public void setPokeDesc()
    {
        try
        {
            String pokeInfoSQL = "select dexno, pokename, height, weight, type1, type2, bodyshape from main_puchamones where dexno = "+current;
			String pokeDescsSQL = "select pokedescriptionrb, pokedescriptiongold, pokedescriptionsilver, pokedescriptioncrystal, pokedescriptionruby, pokedescriptionsaphire, pokedescriptionemerald, pokedescriptiondiamond, pokedescriptionpearl, pokedescriptionplatinum, pokedescriptionhg, pokedescriptionss, pokedescriptionwhite, pokedescriptionblack, pokedescriptionw2, pokedescriptionx, pokedescriptiony, pokedescriptionor, pokedescriptionas, POKEDESCRIPTIONSUN, pokedescriptionmoon, pokedescriptionus, pokedescriptionum from main_puchamones where dexno = "+current;
            rs2 = state2.executeQuery(pokeInfoSQL);
            rs2.first();
			pokeDescs.clear();
			descs = stateD.executeQuery(pokeDescsSQL);
			descs.first();
			
			for(int i = 1; i <= 23; i++)
				if(descs.getString(i) != null)
					pokeDescs.add(descs.getString(i));
				
			descriptions = pokeDescs.toArray(new String[0]);
			
			rotated = shiny = false;
			
			currentDescription = 0;
			prevDesc.setVisible(false);
			
			if(currentDescription < (descriptions.length - 1))
				nextDesc.setVisible(true);
			else
				nextDesc.setVisible(false);
			
			if(descriptions[currentDescription] != null)
				dexcription.setText(descriptions[currentDescription]);
			
			pokeSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/sprites/"+Integer.parseInt(rs2.getString("DEXNO"))+".png")));
			
			if(Integer.parseInt(rs2.getString("bodyshape")) < 10)
				pokeShape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPackage/Images/shapes/Body0"+rs2.getString("bodyshape").toLowerCase()+".png")));
								
            PokeInfoName.setText(rs2.getString("POKENAME"));
            PokeTypeLabel1.setText(rs2.getString("Type1")); 
            switch(rs2.getString("Type1").toLowerCase())
            {
                case "grass":
                    PokeType1.setBackground(grassC);
				break;

				case "fire":
					PokeType1.setBackground(fireC);
					break;

				case "water":
					PokeType1.setBackground(waterC);
					break;

				case "normal":
					PokeType1.setBackground(normalC);
					break;

				case "fighting":
					PokeType1.setBackground(fightingC);
					break;
				
				case "flying":
					PokeType1.setBackground(flyingC);
					break;
					
				case "electric":
					PokeType1.setBackground(electricC);
					break;
				
				case "ground":
					PokeType1.setBackground(groundC);
					break;
				
				case "ice":
					PokeType1.setBackground(iceC);
					break;
				
				case "rock":
					PokeType1.setBackground(rockC);
					break;
				
				case "psychic":
					PokeType1.setBackground(psychicC);
					break;
				
				case "ghost":
					PokeType1.setBackground(ghostC);
					break;
					
				case "dark":
					PokeType1.setBackground(darkC);
					break;
					
				case "bug":
					PokeType1.setBackground(bugC);
					break;
				
				case "poison":
					PokeType1.setBackground(poisonC);
					break;
					
				case "steel":
					PokeType1.setBackground(steelC);
					break;
					
				case "fairy":
					PokeType1.setBackground(fairyC);
					break;
					
				case "dragon":
					PokeType1.setBackground(dragonC);
					break;
            }
            if(rs2.getString("Type2") != null)
            {
                PokeType2.setVisible(true);
                PokeTypeLabel2.setText(rs2.getString("Type2"));
				switch(rs2.getString("Type2").toLowerCase())
				{
					case "grass":
						PokeType2.setBackground(grassC);
					break;

					case "fire":
						PokeType2.setBackground(fireC);
						break;

					case "water":
						PokeType2.setBackground(waterC);
						break;

					case "normal":
						PokeType2.setBackground(normalC);
						break;

					case "fighting":
						PokeType2.setBackground(fightingC);
						break;

					case "flying":
						PokeType2.setBackground(flyingC);
						break;

					case "electric":
						PokeType2.setBackground(electricC);
						break;

					case "ground":
						PokeType2.setBackground(groundC);
						break;

					case "ice":
						PokeType2.setBackground(iceC);
						break;

					case "rock":
						PokeType2.setBackground(rockC);
						break;

					case "psychic":
						PokeType2.setBackground(psychicC);
						break;

					case "ghost":
						PokeType2.setBackground(ghostC);
						break;

					case "dark":
						PokeType2.setBackground(darkC);
						break;

					case "bug":
						PokeType2.setBackground(bugC);
						break;

					case "poison":
						PokeType2.setBackground(poisonC);
						break;

					case "steel":
						PokeType2.setBackground(steelC);
						break;

					case "fairy":
						PokeType2.setBackground(fairyC);
						break;

					case "dragon":
						PokeType2.setBackground(dragonC);
						break;
				}
            }
            else
            {
                PokeType2.setVisible(false);
            }
            if(Integer.parseInt(rs2.getString("DEXNO")) == 1)
            {
                prevPokeInfo.setVisible(false);
            }
            else
                prevPokeInfo.setVisible(true);
            
            if(Integer.parseInt(rs2.getString("DEXNO")) < 10)
                pokeNo.setText("#00"+rs2.getString("DEXNO"));
            else
                if(Integer.parseInt(rs2.getString("DEXNO")) < 100)
                    pokeNo.setText("#0"+rs2.getString("DEXNO"));
            else
                pokeNo.setText(rs2.getString("DEXNO"));
        }
        catch(SQLException e) {System.err.println(e.getMessage());}
    }
	public void setDescriptions()
	{
		dexcription.setText(descriptions[currentDescription]);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PokeInfoName;
    private javax.swing.JPanel PokeType1;
    private javax.swing.JPanel PokeType2;
    private javax.swing.JLabel PokeTypeLabel1;
    private javax.swing.JLabel PokeTypeLabel2;
    private javax.swing.JTextArea dexcription;
    private javax.swing.JScrollPane dexcriptionContainer;
    private javax.swing.JLabel fifthPoke;
    private javax.swing.JLabel fifthPokeImg;
    private javax.swing.JLabel firstPoke;
    private javax.swing.JLabel firstPokeImg;
    private javax.swing.JLabel fourthPoke;
    private javax.swing.JLabel fourthPokeImg;
    private javax.swing.JLabel goDownList;
    private javax.swing.JLabel goUpList;
    private javax.swing.JPanel infoViewPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel listViewPanel;
    private javax.swing.JLabel nextDesc;
    private javax.swing.JLabel nextPokeInfo;
    private javax.swing.JLabel pokeNo;
    private javax.swing.JLabel pokeShape;
    private javax.swing.JLabel pokeSprite;
    private javax.swing.JLabel prevDesc;
    private javax.swing.JLabel prevPokeInfo;
    private javax.swing.JLabel secondPoke;
    private javax.swing.JLabel secondPokeImg;
    private javax.swing.JLabel thirdPoke;
    private javax.swing.JLabel thirdPokeImg;
    // End of variables declaration//GEN-END:variables
}
